version: '3'

services:
  wordpress:
    build: .
    volumes:
      - ./wp-content/:/usr/src/wordpress/wp-content
    links:
      - db:mysql
    labels:
      - "traefik.frontend.rule=Host:wordpress.dev"
      - "traefik.backend=wordpress"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik
